on:
  release:
    types: [published, edited]

name: Build add-on

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build add-on

    steps:
      - name: Check out repository
        uses: actions/checkout@v2.3.4

      - name: Login to DockerHub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name: Login to GitHub Container Registry
      #   uses: docker/login-action@v1.10.0
      #   with:
      #     registry: ghcr.io
      #     username: ${{ secrets.GIT_USER }}
      #     password: ${{ secrets.GIT_TOKEN }}

      - name: Build add-on
        uses: home-assistant/builder@2021.07.0
        with:
          args: |
            ${{ env.BUILD_ARGS }} \
            --all \
            --target /data/camproxy \
            --addon